spring:
  application:
    name: cloud-alibaba-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        enable: false

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: '*'