spring:
  application:
    name: cloud-alibaba-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.222.5:8848
      config:
        enable: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'