server:
  port: 80

admin:
  users:
    -
      id: 1
      name: '张三'
    -
      id: 2
      name: '李四'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
    username: dev
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml