version: '0.0.1'

services:
  mysql:
    image: mysql:5.7
    container_name: dev_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - 'MYSQL_USER=root'
      - 'MYSQL_ROOT_PASSWORD=123456'
    volumes:
      - '~/data/mysql/data:/var/lib/mysql'
      - '~/data/mysql/log:/var/log/mysql'
