spring:
  application:
    name: cloud-alibaba-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: '*'