spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: dev
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

