spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wiki?characterEncoding=utf-8
    username: dev
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    rest:
      uris: http://localhost:9200