dubbo:
  application:
    name: dubbo3_provider
    # qos配置，不配置可能会出现端口冲突
    qos-enable: true
    qos-port: 2222
    qosAcceptForeignIp: false
  protocol:
    name: dubbo
    port: 20881
#  registry:
#    address: zookeeper://localhost:2181
  registries:
    zookeeper:
      address: zookeeper://localhost:2181
      default: false
    nacos:
      address: nacos://localhost:8848
      group: dubbo
      default: true
    nacos2:
      address: nacos://localhost:8858
      group: dubbo
      default: true

server:
  port: 8081