server:
  port: 8002

spring:
  application:
    name: consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: consumer
    prefer-ip-address: true